# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zz4fap/work/timed_comands_for_discontinous_tx/scatter

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zz4fap/work/timed_comands_for_discontinous_tx/scatter/phy

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/zz4fap/work/timed_comands_for_discontinous_tx/scatter/phy/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zz4fap/work/timed_comands_for_discontinous_tx/scatter/phy/CMakeFiles /home/zz4fap/work/timed_comands_for_discontinous_tx/scatter/phy/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zz4fap/work/timed_comands_for_discontinous_tx/scatter/phy/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named anyoption

# Build rule for target.
anyoption: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 anyoption
.PHONY : anyoption

# fast build rule for target.
anyoption/fast:
	$(MAKE) -f anyoption/CMakeFiles/anyoption.dir/build.make anyoption/CMakeFiles/anyoption.dir/build
.PHONY : anyoption/fast

#=============================================================================
# Target rules for targets named logging

# Build rule for target.
logging: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 logging
.PHONY : logging

# fast build rule for target.
logging/fast:
	$(MAKE) -f logging/CMakeFiles/logging.dir/build.make logging/CMakeFiles/logging.dir/build
.PHONY : logging/fast

#=============================================================================
# Target rules for targets named mandates

# Build rule for target.
mandates: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mandates
.PHONY : mandates

# fast build rule for target.
mandates/fast:
	$(MAKE) -f mandates/CMakeFiles/mandates.dir/build.make mandates/CMakeFiles/mandates.dir/build
.PHONY : mandates/fast

#=============================================================================
# Target rules for targets named communicator

# Build rule for target.
communicator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 communicator
.PHONY : communicator

# fast build rule for target.
communicator/fast:
	$(MAKE) -f communicator/CMakeFiles/communicator.dir/build.make communicator/CMakeFiles/communicator.dir/build
.PHONY : communicator/fast

#=============================================================================
# Target rules for targets named communicator_cpp

# Build rule for target.
communicator_cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 communicator_cpp
.PHONY : communicator_cpp

# fast build rule for target.
communicator_cpp/fast:
	$(MAKE) -f communicator/cpp/CMakeFiles/communicator_cpp.dir/build.make communicator/cpp/CMakeFiles/communicator_cpp.dir/build
.PHONY : communicator_cpp/fast

#=============================================================================
# Target rules for targets named module

# Build rule for target.
module: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 module
.PHONY : module

# fast build rule for target.
module/fast:
	$(MAKE) -f module/CMakeFiles/module.dir/build.make module/CMakeFiles/module.dir/build
.PHONY : module/fast

#=============================================================================
# Target rules for targets named module_example

# Build rule for target.
module_example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 module_example
.PHONY : module_example

# fast build rule for target.
module_example/fast:
	$(MAKE) -f module/CMakeFiles/module_example.dir/build.make module/CMakeFiles/module_example.dir/build
.PHONY : module_example/fast

#=============================================================================
# Target rules for targets named mac_layer

# Build rule for target.
mac_layer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mac_layer
.PHONY : mac_layer

# fast build rule for target.
mac_layer/fast:
	$(MAKE) -f mac/CMakeFiles/mac_layer.dir/build.make mac/CMakeFiles/mac_layer.dir/build
.PHONY : mac_layer/fast

#=============================================================================
# Target rules for targets named LinuxInterface

# Build rule for target.
LinuxInterface: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LinuxInterface
.PHONY : LinuxInterface

# fast build rule for target.
LinuxInterface/fast:
	$(MAKE) -f LinuxInterface/CMakeFiles/LinuxInterface.dir/build.make LinuxInterface/CMakeFiles/LinuxInterface.dir/build
.PHONY : LinuxInterface/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f phy/CMakeFiles/uninstall.dir/build.make phy/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) -f phy/CMakeFiles/ContinuousSubmit.dir/build.make phy/CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) -f phy/CMakeFiles/ContinuousCoverage.dir/build.make phy/CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) -f phy/CMakeFiles/ContinuousTest.dir/build.make phy/CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) -f phy/CMakeFiles/ContinuousBuild.dir/build.make phy/CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) -f phy/CMakeFiles/ContinuousMemCheck.dir/build.make phy/CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) -f phy/CMakeFiles/Nightly.dir/build.make phy/CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) -f phy/CMakeFiles/NightlyTest.dir/build.make phy/CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) -f phy/CMakeFiles/NightlyUpdate.dir/build.make phy/CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) -f phy/CMakeFiles/Continuous.dir/build.make phy/CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) -f phy/CMakeFiles/NightlyBuild.dir/build.make phy/CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) -f phy/CMakeFiles/NightlyStart.dir/build.make phy/CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) -f phy/CMakeFiles/NightlyMemoryCheck.dir/build.make phy/CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) -f phy/CMakeFiles/NightlyMemCheck.dir/build.make phy/CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) -f phy/CMakeFiles/ExperimentalStart.dir/build.make phy/CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) -f phy/CMakeFiles/ContinuousConfigure.dir/build.make phy/CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) -f phy/CMakeFiles/NightlyCoverage.dir/build.make phy/CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) -f phy/CMakeFiles/ExperimentalUpdate.dir/build.make phy/CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) -f phy/CMakeFiles/ExperimentalConfigure.dir/build.make phy/CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) -f phy/CMakeFiles/ExperimentalCoverage.dir/build.make phy/CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) -f phy/CMakeFiles/ExperimentalBuild.dir/build.make phy/CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) -f phy/CMakeFiles/NightlyConfigure.dir/build.make phy/CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) -f phy/CMakeFiles/ExperimentalTest.dir/build.make phy/CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) -f phy/CMakeFiles/ExperimentalMemCheck.dir/build.make phy/CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) -f phy/CMakeFiles/Experimental.dir/build.make phy/CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) -f phy/CMakeFiles/NightlySubmit.dir/build.make phy/CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) -f phy/CMakeFiles/ExperimentalSubmit.dir/build.make phy/CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) -f phy/CMakeFiles/ContinuousStart.dir/build.make phy/CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) -f phy/CMakeFiles/ContinuousUpdate.dir/build.make phy/CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named add_srslte_headers

# Build rule for target.
add_srslte_headers: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 add_srslte_headers
.PHONY : add_srslte_headers

# fast build rule for target.
add_srslte_headers/fast:
	$(MAKE) -f phy/srslte/CMakeFiles/add_srslte_headers.dir/build.make phy/srslte/CMakeFiles/add_srslte_headers.dir/build
.PHONY : add_srslte_headers/fast

#=============================================================================
# Target rules for targets named srslte

# Build rule for target.
srslte: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 srslte
.PHONY : srslte

# fast build rule for target.
srslte/fast:
	$(MAKE) -f phy/srslte/lib/CMakeFiles/srslte.dir/build.make phy/srslte/lib/CMakeFiles/srslte.dir/build
.PHONY : srslte/fast

#=============================================================================
# Target rules for targets named srslte_agc

# Build rule for target.
srslte_agc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 srslte_agc
.PHONY : srslte_agc

# fast build rule for target.
srslte_agc/fast:
	$(MAKE) -f phy/srslte/lib/agc/CMakeFiles/srslte_agc.dir/build.make phy/srslte/lib/agc/CMakeFiles/srslte_agc.dir/build
.PHONY : srslte_agc/fast

#=============================================================================
# Target rules for targets named srslte_ch_estimation

# Build rule for target.
srslte_ch_estimation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 srslte_ch_estimation
.PHONY : srslte_ch_estimation

# fast build rule for target.
srslte_ch_estimation/fast:
	$(MAKE) -f phy/srslte/lib/ch_estimation/CMakeFiles/srslte_ch_estimation.dir/build.make phy/srslte/lib/ch_estimation/CMakeFiles/srslte_ch_estimation.dir/build
.PHONY : srslte_ch_estimation/fast

#=============================================================================
# Target rules for targets named refsignal_ul_test_all

# Build rule for target.
refsignal_ul_test_all: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 refsignal_ul_test_all
.PHONY : refsignal_ul_test_all

# fast build rule for target.
refsignal_ul_test_all/fast:
	$(MAKE) -f phy/srslte/lib/ch_estimation/test/CMakeFiles/refsignal_ul_test_all.dir/build.make phy/srslte/lib/ch_estimation/test/CMakeFiles/refsignal_ul_test_all.dir/build
.PHONY : refsignal_ul_test_all/fast

#=============================================================================
# Target rules for targets named chest_test_ul

# Build rule for target.
chest_test_ul: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 chest_test_ul
.PHONY : chest_test_ul

# fast build rule for target.
chest_test_ul/fast:
	$(MAKE) -f phy/srslte/lib/ch_estimation/test/CMakeFiles/chest_test_ul.dir/build.make phy/srslte/lib/ch_estimation/test/CMakeFiles/chest_test_ul.dir/build
.PHONY : chest_test_ul/fast

#=============================================================================
# Target rules for targets named chest_test_dl

# Build rule for target.
chest_test_dl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 chest_test_dl
.PHONY : chest_test_dl

# fast build rule for target.
chest_test_dl/fast:
	$(MAKE) -f phy/srslte/lib/ch_estimation/test/CMakeFiles/chest_test_dl.dir/build.make phy/srslte/lib/ch_estimation/test/CMakeFiles/chest_test_dl.dir/build
.PHONY : chest_test_dl/fast

#=============================================================================
# Target rules for targets named srslte_common

# Build rule for target.
srslte_common: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 srslte_common
.PHONY : srslte_common

# fast build rule for target.
srslte_common/fast:
	$(MAKE) -f phy/srslte/lib/common/CMakeFiles/srslte_common.dir/build.make phy/srslte/lib/common/CMakeFiles/srslte_common.dir/build
.PHONY : srslte_common/fast

#=============================================================================
# Target rules for targets named srslte_fec

# Build rule for target.
srslte_fec: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 srslte_fec
.PHONY : srslte_fec

# fast build rule for target.
srslte_fec/fast:
	$(MAKE) -f phy/srslte/lib/fec/CMakeFiles/srslte_fec.dir/build.make phy/srslte/lib/fec/CMakeFiles/srslte_fec.dir/build
.PHONY : srslte_fec/fast

#=============================================================================
# Target rules for targets named rm_turbo_test

# Build rule for target.
rm_turbo_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rm_turbo_test
.PHONY : rm_turbo_test

# fast build rule for target.
rm_turbo_test/fast:
	$(MAKE) -f phy/srslte/lib/fec/test/CMakeFiles/rm_turbo_test.dir/build.make phy/srslte/lib/fec/test/CMakeFiles/rm_turbo_test.dir/build
.PHONY : rm_turbo_test/fast

#=============================================================================
# Target rules for targets named turbocoder_test

# Build rule for target.
turbocoder_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 turbocoder_test
.PHONY : turbocoder_test

# fast build rule for target.
turbocoder_test/fast:
	$(MAKE) -f phy/srslte/lib/fec/test/CMakeFiles/turbocoder_test.dir/build.make phy/srslte/lib/fec/test/CMakeFiles/turbocoder_test.dir/build
.PHONY : turbocoder_test/fast

#=============================================================================
# Target rules for targets named rm_conv_test

# Build rule for target.
rm_conv_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rm_conv_test
.PHONY : rm_conv_test

# fast build rule for target.
rm_conv_test/fast:
	$(MAKE) -f phy/srslte/lib/fec/test/CMakeFiles/rm_conv_test.dir/build.make phy/srslte/lib/fec/test/CMakeFiles/rm_conv_test.dir/build
.PHONY : rm_conv_test/fast

#=============================================================================
# Target rules for targets named viterbi_test

# Build rule for target.
viterbi_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 viterbi_test
.PHONY : viterbi_test

# fast build rule for target.
viterbi_test/fast:
	$(MAKE) -f phy/srslte/lib/fec/test/CMakeFiles/viterbi_test.dir/build.make phy/srslte/lib/fec/test/CMakeFiles/viterbi_test.dir/build
.PHONY : viterbi_test/fast

#=============================================================================
# Target rules for targets named crc_test

# Build rule for target.
crc_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 crc_test
.PHONY : crc_test

# fast build rule for target.
crc_test/fast:
	$(MAKE) -f phy/srslte/lib/fec/test/CMakeFiles/crc_test.dir/build.make phy/srslte/lib/fec/test/CMakeFiles/crc_test.dir/build
.PHONY : crc_test/fast

#=============================================================================
# Target rules for targets named turbodecoder_test

# Build rule for target.
turbodecoder_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 turbodecoder_test
.PHONY : turbodecoder_test

# fast build rule for target.
turbodecoder_test/fast:
	$(MAKE) -f phy/srslte/lib/fec/test/CMakeFiles/turbodecoder_test.dir/build.make phy/srslte/lib/fec/test/CMakeFiles/turbodecoder_test.dir/build
.PHONY : turbodecoder_test/fast

#=============================================================================
# Target rules for targets named srslte_mimo

# Build rule for target.
srslte_mimo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 srslte_mimo
.PHONY : srslte_mimo

# fast build rule for target.
srslte_mimo/fast:
	$(MAKE) -f phy/srslte/lib/mimo/CMakeFiles/srslte_mimo.dir/build.make phy/srslte/lib/mimo/CMakeFiles/srslte_mimo.dir/build
.PHONY : srslte_mimo/fast

#=============================================================================
# Target rules for targets named layermap_test

# Build rule for target.
layermap_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 layermap_test
.PHONY : layermap_test

# fast build rule for target.
layermap_test/fast:
	$(MAKE) -f phy/srslte/lib/mimo/test/CMakeFiles/layermap_test.dir/build.make phy/srslte/lib/mimo/test/CMakeFiles/layermap_test.dir/build
.PHONY : layermap_test/fast

#=============================================================================
# Target rules for targets named precoding_test

# Build rule for target.
precoding_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 precoding_test
.PHONY : precoding_test

# fast build rule for target.
precoding_test/fast:
	$(MAKE) -f phy/srslte/lib/mimo/test/CMakeFiles/precoding_test.dir/build.make phy/srslte/lib/mimo/test/CMakeFiles/precoding_test.dir/build
.PHONY : precoding_test/fast

#=============================================================================
# Target rules for targets named srslte_phch

# Build rule for target.
srslte_phch: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 srslte_phch
.PHONY : srslte_phch

# fast build rule for target.
srslte_phch/fast:
	$(MAKE) -f phy/srslte/lib/phch/CMakeFiles/srslte_phch.dir/build.make phy/srslte/lib/phch/CMakeFiles/srslte_phch.dir/build
.PHONY : srslte_phch/fast

#=============================================================================
# Target rules for targets named pdsch_test

# Build rule for target.
pdsch_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pdsch_test
.PHONY : pdsch_test

# fast build rule for target.
pdsch_test/fast:
	$(MAKE) -f phy/srslte/lib/phch/test/CMakeFiles/pdsch_test.dir/build.make phy/srslte/lib/phch/test/CMakeFiles/pdsch_test.dir/build
.PHONY : pdsch_test/fast

#=============================================================================
# Target rules for targets named prach_test_usrp

# Build rule for target.
prach_test_usrp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prach_test_usrp
.PHONY : prach_test_usrp

# fast build rule for target.
prach_test_usrp/fast:
	$(MAKE) -f phy/srslte/lib/phch/test/CMakeFiles/prach_test_usrp.dir/build.make phy/srslte/lib/phch/test/CMakeFiles/prach_test_usrp.dir/build
.PHONY : prach_test_usrp/fast

#=============================================================================
# Target rules for targets named pdsch_pdcch_file_test

# Build rule for target.
pdsch_pdcch_file_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pdsch_pdcch_file_test
.PHONY : pdsch_pdcch_file_test

# fast build rule for target.
pdsch_pdcch_file_test/fast:
	$(MAKE) -f phy/srslte/lib/phch/test/CMakeFiles/pdsch_pdcch_file_test.dir/build.make phy/srslte/lib/phch/test/CMakeFiles/pdsch_pdcch_file_test.dir/build
.PHONY : pdsch_pdcch_file_test/fast

#=============================================================================
# Target rules for targets named phich_file_test

# Build rule for target.
phich_file_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 phich_file_test
.PHONY : phich_file_test

# fast build rule for target.
phich_file_test/fast:
	$(MAKE) -f phy/srslte/lib/phch/test/CMakeFiles/phich_file_test.dir/build.make phy/srslte/lib/phch/test/CMakeFiles/phich_file_test.dir/build
.PHONY : phich_file_test/fast

#=============================================================================
# Target rules for targets named pcfich_file_test

# Build rule for target.
pcfich_file_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pcfich_file_test
.PHONY : pcfich_file_test

# fast build rule for target.
pcfich_file_test/fast:
	$(MAKE) -f phy/srslte/lib/phch/test/CMakeFiles/pcfich_file_test.dir/build.make phy/srslte/lib/phch/test/CMakeFiles/pcfich_file_test.dir/build
.PHONY : pcfich_file_test/fast

#=============================================================================
# Target rules for targets named pbch_test

# Build rule for target.
pbch_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pbch_test
.PHONY : pbch_test

# fast build rule for target.
pbch_test/fast:
	$(MAKE) -f phy/srslte/lib/phch/test/CMakeFiles/pbch_test.dir/build.make phy/srslte/lib/phch/test/CMakeFiles/pbch_test.dir/build
.PHONY : pbch_test/fast

#=============================================================================
# Target rules for targets named pusch_test

# Build rule for target.
pusch_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pusch_test
.PHONY : pusch_test

# fast build rule for target.
pusch_test/fast:
	$(MAKE) -f phy/srslte/lib/phch/test/CMakeFiles/pusch_test.dir/build.make phy/srslte/lib/phch/test/CMakeFiles/pusch_test.dir/build
.PHONY : pusch_test/fast

#=============================================================================
# Target rules for targets named pbch_file_test

# Build rule for target.
pbch_file_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pbch_file_test
.PHONY : pbch_file_test

# fast build rule for target.
pbch_file_test/fast:
	$(MAKE) -f phy/srslte/lib/phch/test/CMakeFiles/pbch_file_test.dir/build.make phy/srslte/lib/phch/test/CMakeFiles/pbch_file_test.dir/build
.PHONY : pbch_file_test/fast

#=============================================================================
# Target rules for targets named pcfich_test

# Build rule for target.
pcfich_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pcfich_test
.PHONY : pcfich_test

# fast build rule for target.
pcfich_test/fast:
	$(MAKE) -f phy/srslte/lib/phch/test/CMakeFiles/pcfich_test.dir/build.make phy/srslte/lib/phch/test/CMakeFiles/pcfich_test.dir/build
.PHONY : pcfich_test/fast

#=============================================================================
# Target rules for targets named pdcch_test

# Build rule for target.
pdcch_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pdcch_test
.PHONY : pdcch_test

# fast build rule for target.
pdcch_test/fast:
	$(MAKE) -f phy/srslte/lib/phch/test/CMakeFiles/pdcch_test.dir/build.make phy/srslte/lib/phch/test/CMakeFiles/pdcch_test.dir/build
.PHONY : pdcch_test/fast

#=============================================================================
# Target rules for targets named phich_test

# Build rule for target.
phich_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 phich_test
.PHONY : phich_test

# fast build rule for target.
phich_test/fast:
	$(MAKE) -f phy/srslte/lib/phch/test/CMakeFiles/phich_test.dir/build.make phy/srslte/lib/phch/test/CMakeFiles/phich_test.dir/build
.PHONY : phich_test/fast

#=============================================================================
# Target rules for targets named pucch_test

# Build rule for target.
pucch_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pucch_test
.PHONY : pucch_test

# fast build rule for target.
pucch_test/fast:
	$(MAKE) -f phy/srslte/lib/phch/test/CMakeFiles/pucch_test.dir/build.make phy/srslte/lib/phch/test/CMakeFiles/pucch_test.dir/build
.PHONY : pucch_test/fast

#=============================================================================
# Target rules for targets named prach_test

# Build rule for target.
prach_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prach_test
.PHONY : prach_test

# fast build rule for target.
prach_test/fast:
	$(MAKE) -f phy/srslte/lib/phch/test/CMakeFiles/prach_test.dir/build.make phy/srslte/lib/phch/test/CMakeFiles/prach_test.dir/build
.PHONY : prach_test/fast

#=============================================================================
# Target rules for targets named prach_test_multi

# Build rule for target.
prach_test_multi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prach_test_multi
.PHONY : prach_test_multi

# fast build rule for target.
prach_test_multi/fast:
	$(MAKE) -f phy/srslte/lib/phch/test/CMakeFiles/prach_test_multi.dir/build.make phy/srslte/lib/phch/test/CMakeFiles/prach_test_multi.dir/build
.PHONY : prach_test_multi/fast

#=============================================================================
# Target rules for targets named pdcch_file_test

# Build rule for target.
pdcch_file_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pdcch_file_test
.PHONY : pdcch_file_test

# fast build rule for target.
pdcch_file_test/fast:
	$(MAKE) -f phy/srslte/lib/phch/test/CMakeFiles/pdcch_file_test.dir/build.make phy/srslte/lib/phch/test/CMakeFiles/pdcch_file_test.dir/build
.PHONY : pdcch_file_test/fast

#=============================================================================
# Target rules for targets named srslte_rf

# Build rule for target.
srslte_rf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 srslte_rf
.PHONY : srslte_rf

# fast build rule for target.
srslte_rf/fast:
	$(MAKE) -f phy/srslte/lib/rf/CMakeFiles/srslte_rf.dir/build.make phy/srslte/lib/rf/CMakeFiles/srslte_rf.dir/build
.PHONY : srslte_rf/fast

#=============================================================================
# Target rules for targets named srslte_sync

# Build rule for target.
srslte_sync: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 srslte_sync
.PHONY : srslte_sync

# fast build rule for target.
srslte_sync/fast:
	$(MAKE) -f phy/srslte/lib/sync/CMakeFiles/srslte_sync.dir/build.make phy/srslte/lib/sync/CMakeFiles/srslte_sync.dir/build
.PHONY : srslte_sync/fast

#=============================================================================
# Target rules for targets named pss_usrp_test

# Build rule for target.
pss_usrp_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pss_usrp_test
.PHONY : pss_usrp_test

# fast build rule for target.
pss_usrp_test/fast:
	$(MAKE) -f phy/srslte/lib/sync/test/CMakeFiles/pss_usrp_test.dir/build.make phy/srslte/lib/sync/test/CMakeFiles/pss_usrp_test.dir/build
.PHONY : pss_usrp_test/fast

#=============================================================================
# Target rules for targets named pss_usrp

# Build rule for target.
pss_usrp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pss_usrp
.PHONY : pss_usrp

# fast build rule for target.
pss_usrp/fast:
	$(MAKE) -f phy/srslte/lib/sync/test/CMakeFiles/pss_usrp.dir/build.make phy/srslte/lib/sync/test/CMakeFiles/pss_usrp.dir/build
.PHONY : pss_usrp/fast

#=============================================================================
# Target rules for targets named pss_file

# Build rule for target.
pss_file: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pss_file
.PHONY : pss_file

# fast build rule for target.
pss_file/fast:
	$(MAKE) -f phy/srslte/lib/sync/test/CMakeFiles/pss_file.dir/build.make phy/srslte/lib/sync/test/CMakeFiles/pss_file.dir/build
.PHONY : pss_file/fast

#=============================================================================
# Target rules for targets named cfo_test

# Build rule for target.
cfo_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cfo_test
.PHONY : cfo_test

# fast build rule for target.
cfo_test/fast:
	$(MAKE) -f phy/srslte/lib/sync/test/CMakeFiles/cfo_test.dir/build.make phy/srslte/lib/sync/test/CMakeFiles/cfo_test.dir/build
.PHONY : cfo_test/fast

#=============================================================================
# Target rules for targets named sync_test

# Build rule for target.
sync_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sync_test
.PHONY : sync_test

# fast build rule for target.
sync_test/fast:
	$(MAKE) -f phy/srslte/lib/sync/test/CMakeFiles/sync_test.dir/build.make phy/srslte/lib/sync/test/CMakeFiles/sync_test.dir/build
.PHONY : sync_test/fast

#=============================================================================
# Target rules for targets named srslte_utils

# Build rule for target.
srslte_utils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 srslte_utils
.PHONY : srslte_utils

# fast build rule for target.
srslte_utils/fast:
	$(MAKE) -f phy/srslte/lib/utils/CMakeFiles/srslte_utils.dir/build.make phy/srslte/lib/utils/CMakeFiles/srslte_utils.dir/build
.PHONY : srslte_utils/fast

#=============================================================================
# Target rules for targets named dft_test

# Build rule for target.
dft_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dft_test
.PHONY : dft_test

# fast build rule for target.
dft_test/fast:
	$(MAKE) -f phy/srslte/lib/utils/test/CMakeFiles/dft_test.dir/build.make phy/srslte/lib/utils/test/CMakeFiles/dft_test.dir/build
.PHONY : dft_test/fast

#=============================================================================
# Target rules for targets named srslte_channel

# Build rule for target.
srslte_channel: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 srslte_channel
.PHONY : srslte_channel

# fast build rule for target.
srslte_channel/fast:
	$(MAKE) -f phy/srslte/lib/channel/CMakeFiles/srslte_channel.dir/build.make phy/srslte/lib/channel/CMakeFiles/srslte_channel.dir/build
.PHONY : srslte_channel/fast

#=============================================================================
# Target rules for targets named srslte_dft

# Build rule for target.
srslte_dft: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 srslte_dft
.PHONY : srslte_dft

# fast build rule for target.
srslte_dft/fast:
	$(MAKE) -f phy/srslte/lib/dft/CMakeFiles/srslte_dft.dir/build.make phy/srslte/lib/dft/CMakeFiles/srslte_dft.dir/build
.PHONY : srslte_dft/fast

#=============================================================================
# Target rules for targets named ofdm_test

# Build rule for target.
ofdm_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ofdm_test
.PHONY : ofdm_test

# fast build rule for target.
ofdm_test/fast:
	$(MAKE) -f phy/srslte/lib/dft/test/CMakeFiles/ofdm_test.dir/build.make phy/srslte/lib/dft/test/CMakeFiles/ofdm_test.dir/build
.PHONY : ofdm_test/fast

#=============================================================================
# Target rules for targets named srslte_io

# Build rule for target.
srslte_io: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 srslte_io
.PHONY : srslte_io

# fast build rule for target.
srslte_io/fast:
	$(MAKE) -f phy/srslte/lib/io/CMakeFiles/srslte_io.dir/build.make phy/srslte/lib/io/CMakeFiles/srslte_io.dir/build
.PHONY : srslte_io/fast

#=============================================================================
# Target rules for targets named srslte_modem

# Build rule for target.
srslte_modem: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 srslte_modem
.PHONY : srslte_modem

# fast build rule for target.
srslte_modem/fast:
	$(MAKE) -f phy/srslte/lib/modem/CMakeFiles/srslte_modem.dir/build.make phy/srslte/lib/modem/CMakeFiles/srslte_modem.dir/build
.PHONY : srslte_modem/fast

#=============================================================================
# Target rules for targets named modem_test

# Build rule for target.
modem_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 modem_test
.PHONY : modem_test

# fast build rule for target.
modem_test/fast:
	$(MAKE) -f phy/srslte/lib/modem/test/CMakeFiles/modem_test.dir/build.make phy/srslte/lib/modem/test/CMakeFiles/modem_test.dir/build
.PHONY : modem_test/fast

#=============================================================================
# Target rules for targets named soft_demod_test

# Build rule for target.
soft_demod_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 soft_demod_test
.PHONY : soft_demod_test

# fast build rule for target.
soft_demod_test/fast:
	$(MAKE) -f phy/srslte/lib/modem/test/CMakeFiles/soft_demod_test.dir/build.make phy/srslte/lib/modem/test/CMakeFiles/soft_demod_test.dir/build
.PHONY : soft_demod_test/fast

#=============================================================================
# Target rules for targets named srslte_resampling

# Build rule for target.
srslte_resampling: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 srslte_resampling
.PHONY : srslte_resampling

# fast build rule for target.
srslte_resampling/fast:
	$(MAKE) -f phy/srslte/lib/resampling/CMakeFiles/srslte_resampling.dir/build.make phy/srslte/lib/resampling/CMakeFiles/srslte_resampling.dir/build
.PHONY : srslte_resampling/fast

#=============================================================================
# Target rules for targets named resample_arb_test

# Build rule for target.
resample_arb_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 resample_arb_test
.PHONY : resample_arb_test

# fast build rule for target.
resample_arb_test/fast:
	$(MAKE) -f phy/srslte/lib/resampling/test/CMakeFiles/resample_arb_test.dir/build.make phy/srslte/lib/resampling/test/CMakeFiles/resample_arb_test.dir/build
.PHONY : resample_arb_test/fast

#=============================================================================
# Target rules for targets named resample_arb_bench

# Build rule for target.
resample_arb_bench: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 resample_arb_bench
.PHONY : resample_arb_bench

# fast build rule for target.
resample_arb_bench/fast:
	$(MAKE) -f phy/srslte/lib/resampling/test/CMakeFiles/resample_arb_bench.dir/build.make phy/srslte/lib/resampling/test/CMakeFiles/resample_arb_bench.dir/build
.PHONY : resample_arb_bench/fast

#=============================================================================
# Target rules for targets named srslte_scrambling

# Build rule for target.
srslte_scrambling: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 srslte_scrambling
.PHONY : srslte_scrambling

# fast build rule for target.
srslte_scrambling/fast:
	$(MAKE) -f phy/srslte/lib/scrambling/CMakeFiles/srslte_scrambling.dir/build.make phy/srslte/lib/scrambling/CMakeFiles/srslte_scrambling.dir/build
.PHONY : srslte_scrambling/fast

#=============================================================================
# Target rules for targets named scrambling_test

# Build rule for target.
scrambling_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scrambling_test
.PHONY : scrambling_test

# fast build rule for target.
scrambling_test/fast:
	$(MAKE) -f phy/srslte/lib/scrambling/test/CMakeFiles/scrambling_test.dir/build.make phy/srslte/lib/scrambling/test/CMakeFiles/scrambling_test.dir/build
.PHONY : scrambling_test/fast

#=============================================================================
# Target rules for targets named srslte_ue

# Build rule for target.
srslte_ue: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 srslte_ue
.PHONY : srslte_ue

# fast build rule for target.
srslte_ue/fast:
	$(MAKE) -f phy/srslte/lib/ue/CMakeFiles/srslte_ue.dir/build.make phy/srslte/lib/ue/CMakeFiles/srslte_ue.dir/build
.PHONY : srslte_ue/fast

#=============================================================================
# Target rules for targets named srslte_enb

# Build rule for target.
srslte_enb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 srslte_enb
.PHONY : srslte_enb

# fast build rule for target.
srslte_enb/fast:
	$(MAKE) -f phy/srslte/lib/enb/CMakeFiles/srslte_enb.dir/build.make phy/srslte/lib/enb/CMakeFiles/srslte_enb.dir/build
.PHONY : srslte_enb/fast

#=============================================================================
# Target rules for targets named srslte_rf_monitor

# Build rule for target.
srslte_rf_monitor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 srslte_rf_monitor
.PHONY : srslte_rf_monitor

# fast build rule for target.
srslte_rf_monitor/fast:
	$(MAKE) -f phy/srslte/lib/rf_monitor/CMakeFiles/srslte_rf_monitor.dir/build.make phy/srslte/lib/rf_monitor/CMakeFiles/srslte_rf_monitor.dir/build
.PHONY : srslte_rf_monitor/fast

#=============================================================================
# Target rules for targets named pdsch_enodeb

# Build rule for target.
pdsch_enodeb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pdsch_enodeb
.PHONY : pdsch_enodeb

# fast build rule for target.
pdsch_enodeb/fast:
	$(MAKE) -f phy/srslte/examples/CMakeFiles/pdsch_enodeb.dir/build.make phy/srslte/examples/CMakeFiles/pdsch_enodeb.dir/build
.PHONY : pdsch_enodeb/fast

#=============================================================================
# Target rules for targets named synch_file

# Build rule for target.
synch_file: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 synch_file
.PHONY : synch_file

# fast build rule for target.
synch_file/fast:
	$(MAKE) -f phy/srslte/examples/CMakeFiles/synch_file.dir/build.make phy/srslte/examples/CMakeFiles/synch_file.dir/build
.PHONY : synch_file/fast

#=============================================================================
# Target rules for targets named pdsch_ue

# Build rule for target.
pdsch_ue: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pdsch_ue
.PHONY : pdsch_ue

# fast build rule for target.
pdsch_ue/fast:
	$(MAKE) -f phy/srslte/examples/CMakeFiles/pdsch_ue.dir/build.make phy/srslte/examples/CMakeFiles/pdsch_ue.dir/build
.PHONY : pdsch_ue/fast

#=============================================================================
# Target rules for targets named test_communicator

# Build rule for target.
test_communicator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_communicator
.PHONY : test_communicator

# fast build rule for target.
test_communicator/fast:
	$(MAKE) -f phy/srslte/examples/CMakeFiles/test_communicator.dir/build.make phy/srslte/examples/CMakeFiles/test_communicator.dir/build
.PHONY : test_communicator/fast

#=============================================================================
# Target rules for targets named pdsch_enodeb_pkt

# Build rule for target.
pdsch_enodeb_pkt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pdsch_enodeb_pkt
.PHONY : pdsch_enodeb_pkt

# fast build rule for target.
pdsch_enodeb_pkt/fast:
	$(MAKE) -f phy/srslte/examples/CMakeFiles/pdsch_enodeb_pkt.dir/build.make phy/srslte/examples/CMakeFiles/pdsch_enodeb_pkt.dir/build
.PHONY : pdsch_enodeb_pkt/fast

#=============================================================================
# Target rules for targets named check_tx_timestamps

# Build rule for target.
check_tx_timestamps: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check_tx_timestamps
.PHONY : check_tx_timestamps

# fast build rule for target.
check_tx_timestamps/fast:
	$(MAKE) -f phy/srslte/examples/CMakeFiles/check_tx_timestamps.dir/build.make phy/srslte/examples/CMakeFiles/check_tx_timestamps.dir/build
.PHONY : check_tx_timestamps/fast

#=============================================================================
# Target rules for targets named test_fft

# Build rule for target.
test_fft: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_fft
.PHONY : test_fft

# fast build rule for target.
test_fft/fast:
	$(MAKE) -f phy/srslte/examples/CMakeFiles/test_fft.dir/build.make phy/srslte/examples/CMakeFiles/test_fft.dir/build
.PHONY : test_fft/fast

#=============================================================================
# Target rules for targets named trx

# Build rule for target.
trx: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 trx
.PHONY : trx

# fast build rule for target.
trx/fast:
	$(MAKE) -f phy/srslte/examples/CMakeFiles/trx.dir/build.make phy/srslte/examples/CMakeFiles/trx.dir/build
.PHONY : trx/fast

#=============================================================================
# Target rules for targets named read_dumped_file

# Build rule for target.
read_dumped_file: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 read_dumped_file
.PHONY : read_dumped_file

# fast build rule for target.
read_dumped_file/fast:
	$(MAKE) -f phy/srslte/examples/CMakeFiles/read_dumped_file.dir/build.make phy/srslte/examples/CMakeFiles/read_dumped_file.dir/build
.PHONY : read_dumped_file/fast

#=============================================================================
# Target rules for targets named test_trx_filter

# Build rule for target.
test_trx_filter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_trx_filter
.PHONY : test_trx_filter

# fast build rule for target.
test_trx_filter/fast:
	$(MAKE) -f phy/srslte/examples/CMakeFiles/test_trx_filter.dir/build.make phy/srslte/examples/CMakeFiles/test_trx_filter.dir/build
.PHONY : test_trx_filter/fast

#=============================================================================
# Target rules for targets named check_discontinous_tx

# Build rule for target.
check_discontinous_tx: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check_discontinous_tx
.PHONY : check_discontinous_tx

# fast build rule for target.
check_discontinous_tx/fast:
	$(MAKE) -f phy/srslte/examples/CMakeFiles/check_discontinous_tx.dir/build.make phy/srslte/examples/CMakeFiles/check_discontinous_tx.dir/build
.PHONY : check_discontinous_tx/fast

#=============================================================================
# Target rules for targets named cell_search

# Build rule for target.
cell_search: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cell_search
.PHONY : cell_search

# fast build rule for target.
cell_search/fast:
	$(MAKE) -f phy/srslte/examples/CMakeFiles/cell_search.dir/build.make phy/srslte/examples/CMakeFiles/cell_search.dir/build
.PHONY : cell_search/fast

#=============================================================================
# Target rules for targets named pdsch_ue_pkt

# Build rule for target.
pdsch_ue_pkt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pdsch_ue_pkt
.PHONY : pdsch_ue_pkt

# fast build rule for target.
pdsch_ue_pkt/fast:
	$(MAKE) -f phy/srslte/examples/CMakeFiles/pdsch_ue_pkt.dir/build.make phy/srslte/examples/CMakeFiles/pdsch_ue_pkt.dir/build
.PHONY : pdsch_ue_pkt/fast

#=============================================================================
# Target rules for targets named usrp_capture

# Build rule for target.
usrp_capture: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 usrp_capture
.PHONY : usrp_capture

# fast build rule for target.
usrp_capture/fast:
	$(MAKE) -f phy/srslte/examples/CMakeFiles/usrp_capture.dir/build.make phy/srslte/examples/CMakeFiles/usrp_capture.dir/build
.PHONY : usrp_capture/fast

#=============================================================================
# Target rules for targets named cell_measurement

# Build rule for target.
cell_measurement: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cell_measurement
.PHONY : cell_measurement

# fast build rule for target.
cell_measurement/fast:
	$(MAKE) -f phy/srslte/examples/CMakeFiles/cell_measurement.dir/build.make phy/srslte/examples/CMakeFiles/cell_measurement.dir/build
.PHONY : cell_measurement/fast

#=============================================================================
# Target rules for targets named usrp_capture_sync

# Build rule for target.
usrp_capture_sync: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 usrp_capture_sync
.PHONY : usrp_capture_sync

# fast build rule for target.
usrp_capture_sync/fast:
	$(MAKE) -f phy/srslte/examples/CMakeFiles/usrp_capture_sync.dir/build.make phy/srslte/examples/CMakeFiles/usrp_capture_sync.dir/build
.PHONY : usrp_capture_sync/fast

#=============================================================================
# Target rules for targets named usrp_txrx

# Build rule for target.
usrp_txrx: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 usrp_txrx
.PHONY : usrp_txrx

# fast build rule for target.
usrp_txrx/fast:
	$(MAKE) -f phy/srslte/examples/CMakeFiles/usrp_txrx.dir/build.make phy/srslte/examples/CMakeFiles/usrp_txrx.dir/build
.PHONY : usrp_txrx/fast

#=============================================================================
# Target rules for targets named pss

# Build rule for target.
pss: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pss
.PHONY : pss

# fast build rule for target.
pss/fast:
	$(MAKE) -f phy/srslte/examples/tutorial_examples/CMakeFiles/pss.dir/build.make phy/srslte/examples/tutorial_examples/CMakeFiles/pss.dir/build
.PHONY : pss/fast

#=============================================================================
# Target rules for targets named simple_tx

# Build rule for target.
simple_tx: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simple_tx
.PHONY : simple_tx

# fast build rule for target.
simple_tx/fast:
	$(MAKE) -f phy/srslte/examples/tutorial_examples/CMakeFiles/simple_tx.dir/build.make phy/srslte/examples/tutorial_examples/CMakeFiles/simple_tx.dir/build
.PHONY : simple_tx/fast

#=============================================================================
# Target rules for targets named gateway_reporter

# Build rule for target.
gateway_reporter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gateway_reporter
.PHONY : gateway_reporter

# fast build rule for target.
gateway_reporter/fast:
	$(MAKE) -f ai/CMakeFiles/gateway_reporter.dir/build.make ai/CMakeFiles/gateway_reporter.dir/build
.PHONY : gateway_reporter/fast

#=============================================================================
# Target rules for targets named ai_layer

# Build rule for target.
ai_layer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ai_layer
.PHONY : ai_layer

# fast build rule for target.
ai_layer/fast:
	$(MAKE) -f ai/CMakeFiles/ai_layer.dir/build.make ai/CMakeFiles/ai_layer.dir/build
.PHONY : ai_layer/fast

#=============================================================================
# Target rules for targets named interAICommunication

# Build rule for target.
interAICommunication: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 interAICommunication
.PHONY : interAICommunication

# fast build rule for target.
interAICommunication/fast:
	$(MAKE) -f ai/CMakeFiles/interAICommunication.dir/build.make ai/CMakeFiles/interAICommunication.dir/build
.PHONY : interAICommunication/fast

#=============================================================================
# Target rules for targets named gateway_communicator

# Build rule for target.
gateway_communicator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gateway_communicator
.PHONY : gateway_communicator

# fast build rule for target.
gateway_communicator/fast:
	$(MAKE) -f ai/CMakeFiles/gateway_communicator.dir/build.make ai/CMakeFiles/gateway_communicator.dir/build
.PHONY : gateway_communicator/fast

#=============================================================================
# Target rules for targets named node_communicator

# Build rule for target.
node_communicator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 node_communicator
.PHONY : node_communicator

# fast build rule for target.
node_communicator/fast:
	$(MAKE) -f ai/CMakeFiles/node_communicator.dir/build.make ai/CMakeFiles/node_communicator.dir/build
.PHONY : node_communicator/fast

#=============================================================================
# Target rules for targets named collaboration_client

# Build rule for target.
collaboration_client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 collaboration_client
.PHONY : collaboration_client

# fast build rule for target.
collaboration_client/fast:
	$(MAKE) -f ai/CMakeFiles/collaboration_client.dir/build.make ai/CMakeFiles/collaboration_client.dir/build
.PHONY : collaboration_client/fast

#=============================================================================
# Target rules for targets named slotselection_ai_module

# Build rule for target.
slotselection_ai_module: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 slotselection_ai_module
.PHONY : slotselection_ai_module

# fast build rule for target.
slotselection_ai_module/fast:
	$(MAKE) -f ai/CMakeFiles/slotselection_ai_module.dir/build.make ai/CMakeFiles/slotselection_ai_module.dir/build
.PHONY : slotselection_ai_module/fast

#=============================================================================
# Target rules for targets named flow_performance_module

# Build rule for target.
flow_performance_module: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 flow_performance_module
.PHONY : flow_performance_module

# fast build rule for target.
flow_performance_module/fast:
	$(MAKE) -f ai/CMakeFiles/flow_performance_module.dir/build.make ai/CMakeFiles/flow_performance_module.dir/build
.PHONY : flow_performance_module/fast

#=============================================================================
# Target rules for targets named mcs_ai_module

# Build rule for target.
mcs_ai_module: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mcs_ai_module
.PHONY : mcs_ai_module

# fast build rule for target.
mcs_ai_module/fast:
	$(MAKE) -f ai/CMakeFiles/mcs_ai_module.dir/build.make ai/CMakeFiles/mcs_ai_module.dir/build
.PHONY : mcs_ai_module/fast

#=============================================================================
# Target rules for targets named channel_ai_module

# Build rule for target.
channel_ai_module: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 channel_ai_module
.PHONY : channel_ai_module

# fast build rule for target.
channel_ai_module/fast:
	$(MAKE) -f ai/CMakeFiles/channel_ai_module.dir/build.make ai/CMakeFiles/channel_ai_module.dir/build
.PHONY : channel_ai_module/fast

#=============================================================================
# Target rules for targets named FileWriter

# Build rule for target.
FileWriter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FileWriter
.PHONY : FileWriter

# fast build rule for target.
FileWriter/fast:
	$(MAKE) -f ai/aimodules/RFMonToFile/CMakeFiles/FileWriter.dir/build.make ai/aimodules/RFMonToFile/CMakeFiles/FileWriter.dir/build
.PHONY : FileWriter/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... package"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... anyoption"
	@echo "... logging"
	@echo "... mandates"
	@echo "... communicator"
	@echo "... communicator_cpp"
	@echo "... module"
	@echo "... module_example"
	@echo "... mac_layer"
	@echo "... LinuxInterface"
	@echo "... uninstall"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousTest"
	@echo "... ContinuousBuild"
	@echo "... ContinuousMemCheck"
	@echo "... Nightly"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... Continuous"
	@echo "... NightlyBuild"
	@echo "... NightlyStart"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ContinuousConfigure"
	@echo "... NightlyCoverage"
	@echo "... ExperimentalUpdate"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalBuild"
	@echo "... NightlyConfigure"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalMemCheck"
	@echo "... Experimental"
	@echo "... NightlySubmit"
	@echo "... ExperimentalSubmit"
	@echo "... ContinuousStart"
	@echo "... ContinuousUpdate"
	@echo "... add_srslte_headers"
	@echo "... srslte"
	@echo "... srslte_agc"
	@echo "... srslte_ch_estimation"
	@echo "... refsignal_ul_test_all"
	@echo "... chest_test_ul"
	@echo "... chest_test_dl"
	@echo "... srslte_common"
	@echo "... srslte_fec"
	@echo "... rm_turbo_test"
	@echo "... turbocoder_test"
	@echo "... rm_conv_test"
	@echo "... viterbi_test"
	@echo "... crc_test"
	@echo "... turbodecoder_test"
	@echo "... srslte_mimo"
	@echo "... layermap_test"
	@echo "... precoding_test"
	@echo "... srslte_phch"
	@echo "... pdsch_test"
	@echo "... prach_test_usrp"
	@echo "... pdsch_pdcch_file_test"
	@echo "... phich_file_test"
	@echo "... pcfich_file_test"
	@echo "... pbch_test"
	@echo "... pusch_test"
	@echo "... pbch_file_test"
	@echo "... pcfich_test"
	@echo "... pdcch_test"
	@echo "... phich_test"
	@echo "... pucch_test"
	@echo "... prach_test"
	@echo "... prach_test_multi"
	@echo "... pdcch_file_test"
	@echo "... srslte_rf"
	@echo "... srslte_sync"
	@echo "... pss_usrp_test"
	@echo "... pss_usrp"
	@echo "... pss_file"
	@echo "... cfo_test"
	@echo "... sync_test"
	@echo "... srslte_utils"
	@echo "... dft_test"
	@echo "... srslte_channel"
	@echo "... srslte_dft"
	@echo "... ofdm_test"
	@echo "... srslte_io"
	@echo "... srslte_modem"
	@echo "... modem_test"
	@echo "... soft_demod_test"
	@echo "... srslte_resampling"
	@echo "... resample_arb_test"
	@echo "... resample_arb_bench"
	@echo "... srslte_scrambling"
	@echo "... scrambling_test"
	@echo "... srslte_ue"
	@echo "... srslte_enb"
	@echo "... srslte_rf_monitor"
	@echo "... pdsch_enodeb"
	@echo "... synch_file"
	@echo "... pdsch_ue"
	@echo "... test_communicator"
	@echo "... pdsch_enodeb_pkt"
	@echo "... check_tx_timestamps"
	@echo "... test_fft"
	@echo "... trx"
	@echo "... read_dumped_file"
	@echo "... test_trx_filter"
	@echo "... check_discontinous_tx"
	@echo "... cell_search"
	@echo "... pdsch_ue_pkt"
	@echo "... usrp_capture"
	@echo "... cell_measurement"
	@echo "... usrp_capture_sync"
	@echo "... usrp_txrx"
	@echo "... pss"
	@echo "... simple_tx"
	@echo "... gateway_reporter"
	@echo "... ai_layer"
	@echo "... interAICommunication"
	@echo "... gateway_communicator"
	@echo "... node_communicator"
	@echo "... collaboration_client"
	@echo "... slotselection_ai_module"
	@echo "... flow_performance_module"
	@echo "... mcs_ai_module"
	@echo "... channel_ai_module"
	@echo "... FileWriter"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

